### ISSUE TITLE
Search function for Korean language does not work.

### ISSUE THREAD

**Issue by cloudshand** [spamwax/alfred-pinboard-rs#138]
'ps 한글' does not work.

**Comment by spamwax** [comment]
I am kinda of surprised. Can you please provide more info:
- what is the bookmark that has the korean word? is it in url, title, tags or description of bookmark? would you mind sharing it?
- what is the keyboard layout/standard you are using?
- what is the "Preferred languages" in System Preferences -> Language and Region?

If you can, enable the debug option of workflow in Alfred and the use the search term. Then share the output in the debug window please?

This is interesting since, in my [tests](https://github.com/spamwax/rusty-pin/blob/26109a38817ae4ad76d7781affc9aae5f919ac78/src/pinboard/api.rs?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L351) we can handle non-english URLs!

**Comment by cloudshand** [comment]
On a Mac, pins works just fine. In Alfred workflow, English works fine, but Korean doesn't search. Refer to the screenshots.
Korean word “쉐우민"

**Comment by spamwax** [comment]
I don't see any screenshots :)

**Comment by cloudshand** [comment]
https://www.craft.do/s/ziC267GFIQgjSU

**Comment by spamwax** [comment]
Thanks, I'll try to replicate but can you please follow my instructions and copy/paste the output of Alfred's debug window here when you enter 'ps 한글'

**Comment by spamwax** [comment]
I added a bookmark for https://blog.daum.net/bolee591/ with a keyword '한글' and it showed me the result!
So I really need to see the debug output.
There is a chance that one of your bookmarks is corrupted by an invalid non-UTF-8 character.
<img width="645" alt="Screen Shot 2022-01-03 at 9 56 29 PM" src="https://user-images.githubusercontent.com/1251233/148003647-689adf0c-76c2-4c2f-82fc-032a40082df6.png">

**Comment by spamwax** [comment]
Does the Korean language have the concept of lower-case/upper-case?
If it does, does it apply to any of the character in the bookmark that doesn't show up in Alferd after 'ps 한글'?

**Comment by CreSeed** [comment]
"ps (english url title)" is available for url search.
But "ps (Korean url title)" is not found.
Only Korean Tags are searched.
I want to search not only tags but also url titles in 'Hangul' language.
Can you help me?

**Comment by spamwax** [comment]
@CreSeed Please open a different issue so I can try and debug your issue.
However, I'll be fixing this issue soon and push a new update, so maybe after that update your problem will be resolved.
