### ISSUE TITLE
existing tags not being found when posting

### ISSUE THREAD

**Issue by AvonGee** [spamwax/alfred-pinboard-rs#153]
Hi. When I post a new bookmark, I type "p tag ... " and when I start to type the "tag" alfred-pinboard-rs briefly shows me "Fetching tags." But it finds nothing. No matter what tag I use, alfred-pinboard-rs gives up and calls it a NEW TAG. I can add my tags and post successfully. But it would be nice to know whether I'm needlessly creating a new tag or whether an existing one would do.

**Comment by spamwax** [comment]
is this started happening lately or it was working before?
Can you open the debug window of the workflow and then try again and share
the content of the debug

**Comment by AvonGee** [comment]
I just installed the workflow and encountered the behaviour on my first usage. Thanks for the quick reply and debug suggestion! I always forget about that.

[[07 14 39.758] Rusty Pin[Script Filter] Queuing argument 'p'.txt](https://github.com/user-attachments/files/18038654/07.14.39.758.Rusty.Pin.Script.Filter.Queuing.argument.p.txt)

**Comment by spamwax** [comment]
I have seen this happen in one of these scenarios:
- user does not have any tags or bookmarks yet
- one of the tags or the bookmarks has an "invalid" character in it that breaks the logic of parsing them and store them locally.

the only way to debug this at this point is to manually find the offending bookmark/tag.

to verify this, you can also first export/backup your entire bookmarks using pinboard's website. then delete them all and just add a single bookmark with a tag using pinboard's website.
then use the workflow to update its local cache by running `pu` and try again. if it works then the above theory is correct.

if you don't wanna do that, the other thing you can check is to use Terminal and run

```shell
cd "~/Library/Caches/com.runningwithcrayons.Alfred/Workflow Data/cc.hamid.alfred-pinboard-rs"
ls -l
```

Then check the size of `pins.cache` and `tags.cache` files. For me they are few hundred kilo-bytes. if yours is very small size or even maybe zero that can be a sign that parsing & storing your bookmarks locally is failing due to weird characters in them.

**Comment by spamwax** [comment]
Upon further reading your debug text, it seems you do not have any tags stored on your pinboard account, is that true?

**Comment by AvonGee** [comment]
I have many many tags! Could a colon be the problematic character? The only non-alphabetic characters I can see are period, hyphen, and colon.

Also my pins.cache is ~831k, my tags.cache is 1 byte.

**EDIT**! Looking more thoroughly, there were various other characters. I'm hunting them down one at a time. But I hope I don't have to get rid of period and hyphen. I have a ton of those.

**Comment by spamwax** [comment]
hyphen and period should be ok.

can you test this in a terminal and see how many tags will be stored in `tags.txt`:

```
curl 'https://api.pinboard.in/v1/tags/get?auth_token=USERNAME:API_TOKEN&format=json' > tags.txt
```
(use your USERNAME:API_TOKEN)

**Comment by AvonGee** [comment]
So that command seemed to work, but the result is a 2 byte file. Does that imply that for some reason the Pinboard API is not returning my list of tags? Actually, here's a weird fact I just noticed that seems related. This is what the right side of my Pinboard page looks like.

<img width="392" alt="Screenshot 2024-12-07 at 09 55 02" src="https://github.com/user-attachments/assets/f4e06e99-8799-46c5-b7a1-a240d28ad240">

But if I click "all tags," or any of the 2, 5, 10, or 20 values, all of the "top tags" that were showing disappear and it just reads, "no tags." I'm starting think that this is not at all the workflow's doing!

And FWIW, my Pinboard account page indicates that after culling special characters I have 822 tags, along with
2 579 bookmarks
0 public
2 526 private
53 unread.

**Comment by spamwax** [comment]
yea, it seems he is doing a big code clean up on the server side which can be the cause of the issue

**Comment by AvonGee** [comment]
The wonky site behaviour has been fixed and pinboard-rs is now working as expected. Thanks for your responsiveness!
