### ISSUE TITLE
Lowercase bookmark titles

### ISSUE THREAD

**Issue by mjknght** [spamwax/alfred-pinboard-rs#31]
Recently discovered this, and was thrilled – it's excellent! I note that bookmark titles always appear all lowercase. Is there a setting for this, if I want to see titles in the case they appear on the Pinboard site? Thanks in advance.

**Comment by spamwax** [comment]
There is no setting for it.
The local cache of bookmarks is stored in lowercase.

**Comment by mjknght** [comment]
OK, thanks for letting me know. It would be a great feature addition, but this is nevertheless a wonderful utility as is.

**Comment by spamwax** [comment]
I think my original rationale was to improve search speed by completely ignoring lower/upper case so the search functions don't have to do extra operations/comparisons. That's why I didn't add complexity to code by keeping two copies of users' bookmarks (one original & one lower-cased)

But I can see the neunacne in changing everything to lowercase.
I'll try to find time & see if this can be added without too much code-change & possible hit to performance.

**Comment by spamwax** [comment]
Release `0.15.7` closes this.
