### ISSUE TITLE
Alfred exits after typing "p" while Firefox is focused

### ISSUE THREAD

**Issue by kingdido999** [spamwax/alfred-pinboard-rs#37]
Thanks for this awesome workflow!

My issue is that Alfred exists (with an alert sound) after I type "p" (basically every commands start with "p") in Alfred while Firefox is focused. If Firefox is not focused, typing "p" and related shortcuts works fine. I'm using a fresh install of this workflow with default configurations.

After some troubleshooting, I see the following known issue in README:

> Firefox: While tag suggestions and "Check if page is bookmarked" options are enabled, posting bookmark from Firefox is broken. Deleting bookmarks using pind won't work when Firefox is your active browser. Reason: Firefox does not properly support interacting with it programatically.

So I set option "Check if page is bookmarked" to false, and now the issue goes away!

However, if I understand it correctly, this enabled option should only break the functionality of posting and deleting bookmark from Firefox. So it was not supposed to cause Alfred to error out and thus make this workflow unusable.

- Alfred version: 4.0.3
- Workflow version: 0.15.7
- Firefox version: 68.0
- MacOS version: 10.14.4

Please let me know if you need more information.

**Comment by spamwax** [comment]
All of "Check if page is bookmarked", delete page and suggest tags require to query fire-fox while you are typing the keywords and arguments. This is needed to get opened tab's info (title/url). As mentioned in README, this is not working and it's very unlikely to be fixed soon by Mozilla.

Posting a bookmark still works, because this workflow fetches title/url after you hit enter which means Alfred window is closed and that's why you don't see/hear any error.
