### ISSUE TITLE
Auth to Pinboard Fails on 10.15.4 and v0.15.11

### ISSUE THREAD

**Issue by ivonesh** [spamwax/alfred-pinboard-rs#59]
Hi, this is my first install of your workflow, I just found it. I've installed v0.15.11 and I'm running Alfred 4, fully up to date, on macOS 10.15.4. I first got a macOS error for an unrecognized developer, but I allowed it via System Preferences > Security & Privacy. 

I have a valid Pinboard account and I even refreshed my API token in trying to fix this error. 

Upon trying to authorize `pa username:token`, I get the large text error on screen. See attached. 

Any ideas what is wrong/why failing? Thanks!

<img width="1440" alt="Screen Shot 2020-03-31 at 4 02 24 PM" src="https://user-images.githubusercontent.com/1063950/78076059-51d79800-736b-11ea-9347-933daa47c9f2.png">

**Comment by spamwax** [comment]
This is most likely due to the fact that one of your bookmarks on pinboard is "corrupted", probably due to a non-unicode character in one of them.

However to narrow down the problem, please post the content of alfred debug window after you enter `pa use:token` command. Make sure you enable "Show All information"

![image](https://user-images.githubusercontent.com/1251233/78113537-e1ae2e00-73cd-11ea-88fc-1883748f9ff9.png)

**Comment by ivonesh** [comment]
Thanks for the quick response. Pinboard was down this morning. After it came back up, I `pa username:token` and everything was ok. I ran the debug and it did not error out. Thanks!

**Comment by Mercurius-Lee** [comment]
I also failed to update the cache . below is the screen capture of the debugging information.
![image](https://user-images.githubusercontent.com/31580811/88073997-715c3000-cba9-11ea-9d52-872eaae0c07d.png)

**Comment by spamwax** [comment]
@Mercurius-Lee this can happen due to pinboard issues as the other user mentioned above.
another less likely reasons can be that:
- you don't have any bookmarks
- you are using an old version of the workflow.
