### ISSUE TITLE
Keep getting Passing output 'Error: Cache: comparing timestamp with server failed'

### ISSUE THREAD

**Issue by dustinth** [spamwax/alfred-pinboard-rs#96]
It seems to be related with time zone?

**Comment by spamwax** [comment]
I am not sure, most of the time these errors are caused by Pinboard having issues on their end.
Please post a full debug output from Alfred here.
- Is this happening on a first-time install or you have been using the workflow for some time now?
- Sometimes people don't have any bookmarks/tags and it can cause issues.
- Have you uninstalled the workflow and cleared the cache/data folders & tired to reinstall it again?
